### ISSUE TITLE
show "starting" text to avoid user confusion

### ISSUE THREAD

**Issue by SkySpnc** [PaciStardust/HOSCY#27]
instead of loading the language model on the same frame as it being clicked, delay the loading of the lang model by ~0.5s and show a big box the user wont be able to miss saying "loading" or "starting". example image provided.
![image](https://user-images.githubusercontent.com/83870752/191866956-3250d999-9218-42fa-aedf-ff2e69dcb8ec.png)

**Comment by PaciStardust** [comment]
Should display mooost times, inconsistent but cant find a better way
