### ISSUE TITLE
Multiple Languages in Azure Speech Recognition Options not supported by API ? 

### ISSUE THREAD

**Issue by marcoboy123** [PaciStardust/HOSCY#37]
23:04:05.929 Warning  [RecognizerAzure.cs::OnCanceled:153] Recognition was cancelled (Reason: Error, Code: BadRequest, Details: Connection was closed by the remote host. Error code: 1007. Error details: Language identification with DetectContinuous not supported on v1. SessionId: ac1e024759c4444bada3b7675db99868)
[Picture](https://puu.sh/Jo1qZ/83714bf653.png)
When putting in any 2 different languages to be recognized it puts this out
I tried it with
en-US
ja-JP
de-DE

Not sure if error just on my part or if you can recreate this

**Comment by PaciStardust** [comment]
Strange. Mind providing the other settings?

**Comment by PaciStardust** [comment]
Fixed in v.0.3.2
