### ISSUE TITLE
Possibility to use nvidia riva api or STT of voice to text recognition  

### ISSUE THREAD

**Issue by DarkVader135** [PaciStardust/HOSCY#38]
adding support for riva api to use a locally hosted riva server to do speech to text recognition i did some digging cuz i am kinda new to AI they called it ASR or STT [jasper STT](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_jasper10x5dr)  [Riva api](https://developer.nvidia.com/riva) i did this post just to bring attention for these option ik implementing nvidia propritary tools won't be the best thing because not everyone has an nvidia gpu at their disposal

**Comment by PaciStardust** [comment]
This appears to not work continously and would not seamlessly interact with HOSCY without any odd workarounds.
