### ISSUE TITLE
I can't use stt

### ISSUE THREAD

**Issue by Superwolf6099** [PaciStardust/HOSCY#40]
It keeps  giving me error code: Unable to connect to Azure Cognitive Services, have you used the correct credentials?

--------------------------
Error details:

Exception with an error code: 0x5

--------------------------
Stack trace:

   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at Hoscy.Services.Speech.Recognizers.RecognizerAzure.TryCreateRecognizer()
I don't know what to do.

**Comment by PaciStardust** [comment]
Have you provided a key and region in the API settings?

**Comment by Superwolf6099** [comment]
I've noticed wrong recognizer but its still not working and I fixed the recognizer and setup the Vosk file to Hoscy.

**Comment by Superwolf6099** [comment]
Error code:Attempted to start model but the picked recognition model file is invalid. Have you downloaded a compatible model, picked the correct folder and verified it is not corrupt?

**Comment by PaciStardust** [comment]
If you are confused about setting up VOSK please refer to either the [quickstart guide](https://github.com/PaciStardust/HOSCY/wiki/Quickstart-Guide) or the [tutorial video](https://www.youtube.com/watch?v=hbMl33J_kYs)

**Comment by PaciStardust** [comment]
Has my previous post solved your issue?

**Comment by PaciStardust** [comment]
Closed due to inactivity
