### ISSUE TITLE
Enhancement: regex/glob blacklist for media api

### ISSUE THREAD

**Issue by Bluscream** [PaciStardust/HOSCY#45]
would be nice if i could blacklist certain apps/websites from appearing in the media thingy. noone needs to know what i watch on xhamster :p

**Comment by PaciStardust** [comment]
I have rewritten filters to add extra functionality:
- Enabling / Disabling individually
- Regex and Case Sensitivity modes

This applies to the logging filter and new media filters

ADDITIONALLY it annoyed me that the filters now had more fine control than replacements and shortcuts, they have also been provided with these new features. 

UI for filters and shortcuts/replacements has also been overhauled slightly.

These changes are also on a testing branch. If everything goes right I can merge and release this weekend.

**Comment by PaciStardust** [comment]
Newest release includes this functionality
