### ISSUE TITLE
Enhancement: more customizable media message

### ISSUE THREAD

**Issue by Bluscream** [PaciStardust/HOSCY#46]
use a single textfield with variables instead of the split sentence

**Comment by PaciStardust** [comment]
I have it split so some parts will not be shown, if the information is not available.

Overcomplicating it with some kind of markup would likely just confuse the normal user. 

Do you have any suggestions on how I could implement this in a user friendly way?

**Comment by PaciStardust** [comment]
Would adding an additional text field for text after everything else suffice?

**Comment by Bluscream** [comment]
> I have it split so some parts will not be shown, if the information is not available.
> 
> Overcomplicating it with some kind of markup would likely just confuse the normal user.
> 
> Do you have any suggestions on how I could implement this in a user friendly way?

Hmm, you're right. I hadn't considered that. The easiest compromise would probably to add a new textfield and a "Advanced/Manual" checkbox, which disables your combination fields and allows overriding it with own text using variables. If you want to keep the conditionals, you might have to come up with your own syntax; maybe smth like a mix between html
```py
"Playing {title}<artist> by {artist}</artist><album> from {album}</album><source> using {source}</source>"
```

**Comment by PaciStardust** [comment]
As source is not a field I have, I have decided to just provide an extra text field for adding text behind. This is implemented in a different branch for testing. A merge and release can be expected this weekend if everything goes according to plan

**Comment by PaciStardust** [comment]
Newest release includes this functionality
