### ISSUE TITLE
Application Crashes When "Output" Button Is Clicked

### ISSUE THREAD

**Issue by HakuSystems** [PaciStardust/HOSCY#48]
Hi there,

I have encountered an issue where the application crashes unexpectedly when I attempt to interact with the "Output" button. This is happening consistently, and I wanted to report this issue and hopefully find a solution for it.

### Description of the Issue
While using the application, each time I click on the "Output" button, the app crashes immediately, displaying either a error screen and closing entirely.

### Steps to reproduce
Launch the application.
Click on the "Output" button.
### Expected behavior
On clicking the "Output" button, I expected the app to work like it should.

### Screenshots or Screen recording
https://f.biyori.moe/kMu6T4.mp4

### Environment
App version: 0.7.1.0
Operating System: Windows 10 Pro

Log File:
[log-06-02-2023-21-11-52.txt](https://github.com/PaciStardust/HOSCY/files/11638210/log-06-02-2023-21-11-52.txt)

**Comment by PaciStardust** [comment]
This is an issue regarding the volume slider and some odd library behavior. Has been around for quite some time and appears to happen randomly... Currently investigating the cause and a possible fix.

**Comment by HakuSystems** [comment]
Hey, this is fixed in the newest version apparently
