### ISSUE TITLE
Compatibility Issue Between HOSCY and VRChat Face Tracking Software Due to Port Conflict

### ISSUE THREAD

**Issue by HakuSystems** [PaciStardust/HOSCY#54]
I've encountered a compatibility issue when using HOSCY alongside VRChat's face tracking software ([VRCFaceTracking](https://github.com/benaclejames/VRCFaceTracking)). The primary concern is that both applications attempt to send data over the same port. Altering the port in HOSCY's settings has not resolved the issue.

## Steps to Reproduce
1. Run VRChat with the [VRCFaceTracking](https://github.com/benaclejames/VRCFaceTracking) software.
2. Run HOSCY.
3. Observe the port conflict.
4. Change the port in HOSCY's settings.
5. Notice that the issue persists despite the port change.

## Current Behavior
There is a port conflict which leads to operational problems in either HOSCY or the VRChat face tracking software, depending on which application is launched first.

## Expected Behavior
Both applications should function simultaneously without port conflicts.

## Additional Information
Any assistance or updates to address this compatibility issue would be greatly appreciated.

Thank you.

**Comment by PaciStardust** [comment]
Could you please provide the error messages for the tools?

**Comment by HakuSystems** [comment]
No Software was giving me errros
